$( proof/subsets/add-element-bijection, elaborated from proof/subsets.proof by parley/elaborate.py.
   Nothing here is assumed.
   Checked against a set.mm of 51,256 assertions, sha256
   0d7fb3e59afff60f4cec2287cbb616bf651bbfbf2356a611a43a5c98b5e0462d. $)

$[ stdlib/definitions.mm $]

${
  $d i j m y $.
  $d A i j m y $.
  $d B i j m y $.
  addeleme $p |- ( ( A e. _V /\ ( B e. _V /\ -. B e. A ) ) -> ~P A ~~ ran ( m e. ~P A |-> ( m u. { B } ) ) ) $=
    ( cvv wcel wn wa cpw cv csn cun cmpt crn wf1o cen wbr simpl id syl pwexg wf1 wral vy wceq wi simpr snex a1i jca unexg ralrimiva vj vi cdif wss wb vex elpwg mpbid ssneld mpd difsn eqcomd difun2 difeq1d eqeq1d eqtrd ex uneq1d eqeq2d imbi12d cbvralvw ralbii ralbidv bitri eqid f1mpt sylibr f1f1orn f1oeng ) ADEZBDEZBAEZFZGZGZAHZDEZWGCWGCIZBJZKZLZMZWLNZGWGWMOPWFWHWNWFWAWHWFWAWAWAWEQWARSADTSWFWGDWLUAZWNWFWKDEZCWGUBZWKUCIZWJKZUDZWIWRUDZUEZUCWGUBZCWGUBZGWOWFWQXDWFWPCWGWFWIWGEZGZXEWJDEZGWPXFXEXGWFXEUFXGXFBUGUHUIWIWJWGDUJSUKWFULIZWJKZUMIZWJKZUDZXHXJUDZUEZUMWGUBZULWGUBZXDWFXOULWGWFXHWGEZGZXNUMWGXRXJWGEZGZXLXMXTXLGZXHXJWJUNZXJYAXHXKWJUNZYBYAXHXHWJUNZYCYAYDXHYABXHEZFZYDXHUDYAWDYFYAWEWDYAXTWEXTXLQZXTXRWEXRXSQZXRWFWEWFXQQZWAWEUFZSZSZSZWBWDUFZSZYAXHABYAXQXHAUOZYAXTXQYGXTXRXQYHWFXQUFSSYAXHDEZXQYPUPYQYAULUQUHXHADURSUSUTVABXHVBSVCYAYCYDYAXIWJUNZYDUDZYCYDUDYSYAXHWJVDUHYAYRYCYDYAXIXKWJXTXLUFVEVFUSVCVGYCYBUDYAXJWJVDUHVGYABXJEZFZYBXJUDYAWDUUAYOYAXJABYAXSXJAUOZYAXTXSYGXRXSUFSYAXJDEZXSUUBUPUUCYAUMUQUHXJADURSUSUTVABXJVBSVGVHUKUKXPXDUPWFXPXIWSUDZXHWRUDZUEZUCWGUBZULWGUBXDXOUUGULWGXNUUFUMUCWGXJWRUDZXLUUDXMUUEUUHXKWSXIUUHXJWRWJUUHRZVIVJUUHXJWRXHUUIVJVKVLVMUUGXCULCWGXHWIUDZUUFXBUCWGUUJUUDWTUUEXAUUJXIWKWSUUJXHWIWJUUJRZVIVFUUJXHWIWRUUKVFVKVNVLVOUHUSUICUCWGDWKWSWLWLVPXAWIWRWJXARVIVQVRWGDWLVSSUIWGWMDWLVTS $.
$}
