$( proof/subsets/powerset-split, elaborated from proof/subsets.proof by parley/elaborate.py.
   Nothing here is assumed.
   Checked against a set.mm of 51,256 assertions, sha256
   0d7fb3e59afff60f4cec2287cbb616bf651bbfbf2356a611a43a5c98b5e0462d. $)

$[ stdlib/definitions.mm $]

${
  $d j k m $.
  $d A j k m $.
  $d B j k m $.
  powerset $p |- ( ( A e. _V /\ B e. A ) -> ~P A = ( ~P ( A \ { B } ) u. ran ( m e. ~P ( A \ { B } ) |-> ( m u. { B } ) ) ) ) $=
    ( cvv wcel wa cpw csn cdif cv cun cmpt crn wss wceq vk wral wn simpl simpr wb vex a1i elpwg syl mpbid ssdif difexg mpbird snex jca unexg eqid id uneq1d elrnmpt1s difsnid eleq1d elun2 ssdifsn sylibr elun1 wo exmid mpjaodan ralrimiva dfss3 difss sspw vj sstr snssi unss sylib cbvralvw rnmptss eqss ) ADEZBAEZFZAGZABHZIZGZCWDCJZWBKZLZMZKZNZWIWANZFWAWIOVTWJWKVTWJPJZWIEZPWAQZVTWMPWAVTWLWAEZFZBWLEZWMWQRZWPWQFZWLWHEZWMWSWLWBIZWBKZWHEZWTWSXAWDEZXBDEZFXCWSXDXEWSXDXAWCNZWSWLANZXFWSWPXGWPWQSZWPWOXGVTWOTZWPWLDEZWOXGUAZXJWPPUBZUCZWLADUDZUEZUFZUEZWLAWBUGZUEZWSXADEZXDXFUAZWSXJXTXJWSXLUCZWLWBDUHZUEZXAWCDUDZUEZUIZWSXDWBDEZFXEWSXDYHYGYHWSBUJZUCUKXAWBWDDULUEUKCWDWFXBXAWGDWGUMZWEXAOZWEXAWBYKUNUOUPUEWSXBWLWHWSWQXBWLOWPWQTWLBUQUEURUFWLWHWDUSUEWPWRFZWLWDEZWMYLYMWLWCNZYLXGWRFYNYLXGWRYLWPXGWPWRSXPUEWPWRTUKWLABUTVAYLXJYMYNUAXJYLXLUCWLWCDUDUEUIWLWDWHVBUEWQWRVCWPWQVDUCVEVFWJWNUAVTPWAWIVGUCUIVTWDWANZWHWANZFWKVTYOYPVTWCANZYOYQVTAWBVHZUCZWCAVIUEVTWFWAEZCWDQZYPVTVJJZWBKZWAEZVJWDQZUUAVTUUDVJWDVTUUBWDEZFZUUDUUCANZUUGUUBANZWBANZFUUHUUGUUIUUJUUGUUBWCNZYQFUUIUUGUUKYQUUGUUFUUKVTUUFTUUGUUBDEZUUFUUKUAUULUUGVJUBZUCZUUBWCDUDUEUFUUGVTYQVTUUFSZYSUEUKUUBWCAVKUEUUGVSUUJUUGVTVSUUOVRVSTUEBAVLUEUKUUBWBAVMVNUUGUUCDEZUUDUUHUAUUGUULYHFUUPUUGUULYHUUNYHUUGYIUCUKUUBWBDDULUEUUCADUDUEUIVFUUEUUAUAVTUUDYTVJCWDUUBWEOZUUCWFWAUUQUUBWEWBUUQUNUOURVOUCUFCWDWFWAWGYJVPUEUKWDWHWAVMVNUKWAWIVQVA $.
$}
