$( stdlib/proved, built by elaboration/stdlib/build-proved.py.

   What the library proves below the readable layer: facts this corpus
   needs, set.mm does not state, and the readable layer cannot. Each group
   stands in a block of its own. $)

$[ stdlib/definitions.mm $]

${
$( Geometry: what this corpus needs of the plane and set.mm does not
   state. Points are complex numbers, distance is the absolute value of a
   difference, and the angle is the constant definitions.mm introduces,
   so everything here is a theorem rather than an axiom: CC is a model
   and nothing in it has to be assumed.  GEOMETRY.md takes that
   decision and says what it costs. $)

$( `angval` reads a value of the angle by substituting for the two names
   `df-ang` binds, and asks that they be free of what is substituted. They
   appear in no statement here, only inside the proofs. The pairs are
   written one at a time because `$d x y A B` would also hold A and B
   apart, and the lemmas below are applied at terms that share names. $)
$d x y $.
$d x A $.  $d y A $.
$d x B $.  $d y B $.
$d x C $.  $d y C $.
$d x P $.  $d y P $.
$d x Q $.  $d y Q $.
$d x R $.  $d y R $.
$d x S $.  $d y S $.
$d x T $.  $d y T $.
$d x U $.  $d y U $.

  gtrirec $p |- ( ( ( A e. CC /\ A =/= 0 ) /\ ( B e. CC /\ B =/= 0 ) ) -> ( ( A / B ) e. RR -> ( B / A ) e. RR ) ) $=
    ( cc wcel cc0 wne wa cdiv co cr c1 wceq recdiv adantr simpr divne0 jca
    rereccl syl eqeltrrd ex )
    ACDZAEFZGZBCDZBEFZGZGZABHIZJDZBAHIZJDUHUJGZKUIHIZUKJUHUMUKLUJABMNULUJUIEFZGUMJDULUJUNUHUJOUHUNUJABPNQUIRSTUA $.

  gtriswap $p |- ( ( A e. CC /\ B e. CC /\ C e. CC ) -> ( ( ( ( -. A = B /\ -. B = C ) /\ -. A = C ) /\ -. ( ( C - A ) / ( B - A ) ) e. RR ) -> ( ( ( -. A = C /\ -. C = B ) /\ -. A = B ) /\ -. ( ( B - A ) / ( C - A ) ) e. RR ) ) ) $=
    ( cc wcel w3a wceq wn wa cmin co cdiv cr simpr simpld simprd neqned
    necomd neneqd jca31 cc0 wne wi simp2 adantr simp1 subcld subeq0ad
    necon3bid mpbird jca simp3 gtrirec syl con3d mpd ex )
    ADEZBDEZCDEZFZABGZHZBCGZHZIZACGZHZIZCAJKZBAJKZLKZMEZHZIZVHCBGZHZIZVCIZVKVJLKZMEZHZIVAVOIZVSWBWCVHVQVCWCVFVHWCVIVNVAVONZOZPZWCCBWCBCWCBCWCVCVEWCVFVHWEOZPQRSWCVCVEWGOZTWCVNWBWCVIVNWDPWCWAVMWCVKDEZVKUAUBZIZVJDEZVJUAUBZIZIWAVMUCWCWKWNWCWIWJWCBAVAUSVOURUSUTUDZUEZVAURVOURUSUTUFZUEZUGWCWJBAUBWCBAWCBAWCABWCABWHQRSQWCVKUABAWCBAWPWRUHUIUJUKWCWLWMWCCAVAUTVOURUSUTULZUEZWRUGWCWMCAUBWCCAWCCAWCACWCACWFQRSQWCVJUACAWCCAWTWRUHUIUJUKUKVKVJUMUNUOUPUKUQ $.

  gtricol $p |- ( ( ( A e. CC /\ B e. CC /\ C e. CC ) /\ ( ( A - B ) =/= 0 /\ ( C - B ) =/= 0 ) ) -> ( ( ( A - B ) / ( C - B ) ) e. RR -> ( ( C - A ) / ( B - A ) ) e. RR ) ) $=
    ( cc wcel w3a cmin co cc0 wne wa cdiv cr c1 cneg wceq simp1 adantr simp3
    subcld simp2 simpl adantl div2neg syl3anc negsubdi2 syl2anc oveq12d
    nnncan2 oveq1d jca divsubdir divid eqtrd eqtr3d 3eqtr3d 1re a1i simpr wi
    gtrirec syl mpd resubcl eqeltrd ex )
    ADEZBDEZCDEZFZABGHZIJZCBGHZIJZKZKZVKVMLHZMEZCAGHZBAGHZLHZMEVPVRKZWANVMVKLHZGHZMWBACGHZOZVKOZLHZWEVKLHZWAWDWBWEDEVKDEZVLWHWIPWBACVPVGVRVJVGVOVGVHVIQZRZRZVPVIVRVJVIVOVGVHVISZRZRZTWBABWMVPVHVRVJVHVOVGVHVIUAZRZRZTZVPVLVRVOVLVJVLVNUBZUCZRZWEVKUDUEWBWFVSWGVTLWBVGVIWFVSPWMWPACUFUGWBVGVHWGVTPWMWSABUFUGUHWBVKVMGHZVKLHZWIWDWBXDWEVKLWBVGVIVHXDWEPWMWPWSACBUIUEUJWBXEVKVKLHZWCGHZWDWBWJVMDEZWJVLKZXEXGPWTWBCBWPWSTZWBWJVLWTXCUKZVKVMVKULUEWBXFNWCGWBWJVLXFNPWTXCVKUMUGUJUNUOUPWBNMEZWCMEZWDMEXLWBUQURWBVRXMVPVRUSWBXIXHVNKZKVRXMUTWBXIXNXKWBXHVNXJVPVNVRVOVNVJVLVNUSUCRUKUKVKVMVAVBVCNWCVDUGVEVF $.

  gtrirotate $p |- ( ( A e. CC /\ B e. CC /\ C e. CC ) -> ( ( ( ( -. A = B /\ -. B = C ) /\ -. A = C ) /\ -. ( ( C - A ) / ( B - A ) ) e. RR ) -> ( ( ( -. B = C /\ -. C = A ) /\ -. B = A ) /\ -. ( ( A - B ) / ( C - B ) ) e. RR ) ) ) $=
    ( cc wcel w3a wceq wn wa cmin co cdiv cr simpr simpld simprd neqned
    necomd neneqd jca31 cc0 wne wi simpl simp1 adantr simp2 subeq0ad
    necon3bid mpbird simp3 jca gtricol syl con3d mpd ex )
    ADEZBDEZCDEZFZABGZHZBCGZHZIZACGZHZIZCAJKZBAJKZLKZMEZHZIZVECAGZHZIZBAGZHZIZABJKZCBJKZLKZMEZHZIVAVOIZWAWFWGVEVQVTWGVCVEWGVFVHWGVIVNVAVONZOZOZPZWGCAWGACWGACWGVFVHWIPQRSWGBAWGABWGABWGVCVEWJOZQZRSTWGVNWFWGVIVNWHPWGWEVMWGVAWBUAUBZWCUAUBZIZIWEVMUCWGVAWPVAVOUDWGWNWOWGWNABUBWMWGWBUAABWGABVAURVOURUSUTUEUFVAUSVOURUSUTUGZUFZUHUIUJWGWOCBUBWGCBWGCBWGBCWGBCWKQRSQWGWCUACBWGCBVAUTVOURUSUTUKUFWRUHUIUJULULABCUMUNUOUPULUQ $.

  gangval $p |- ( ( ( A e. CC /\ A =/= 0 ) /\ ( B e. CC /\ B =/= 0 ) ) -> ( A ang B ) = ( Im ` ( log ` ( B / A ) ) ) ) $=
    ( vx vy cang df-ang angval ) CDABECDFG $.

  gangrec $p |- ( ( ( A e. CC /\ A =/= 0 ) /\ ( B e. CC /\ B =/= 0 ) ) -> ( B ang A ) = ( Im ` ( log ` ( 1 / ( B / A ) ) ) ) ) $=
    ( cc wcel cc0 wne wa cang co cdiv clog cfv cim c1 wceq vx vy df-ang
    angval ancoms simpr simpl jca recdiv syl eqcomd fveq2d eqtrd )
    ACDZAEFZGZBCDZBEFZGZGZBAHIZABJIZKLZMLZNBAJIZJIZKLZMLUNUKUPUSOPQBAHPQRSTUOURVBMUOUQVAKUOVAUQUOUNUKGVAUQOUOUNUKUKUNUAUKUNUBUCBAUDUEUFUGUGUH $.

  gangsym $p |- ( ( ( A e. CC /\ A =/= 0 ) /\ ( B e. CC /\ B =/= 0 ) ) -> ( abs ` ( A ang B ) ) = ( abs ` ( B ang A ) ) ) $=
    ( cc wcel cc0 wne wa cdiv co clog cfv cim cabs c1 cang cneg crp wceq cpi
    simpr wb simpld simpl simprd divcl syl3anc adantr jca divne0 syl lognegb
    syl2anc mpbid fveq2d ax-1cn a1i divneg2 eqcomd rpreccl eqeltrrd reccld
    recne0d eqtr4d wn arginv cr logcld imcl recn absneg eqtrd pm2.61dan vx vy
    df-ang angval ancoms recdiv 3eqtr4d )
    ACDZAEFZGZBCDZBEFZGZGZBAHIZJKZLKZMKZNWGHIZJKZLKZMKZABOIZMKBAOIZMKWFWGPZQDZWJWNRWFWRGZWJSMKWNWSWISMWSWRWISRZWFWRTZWSWGCDZWGEFZWRWTUAWFXBWRWFWCVTWAXBWFWCWDWBWETZUBZWFVTWAWBWEUCZUBZWFVTWAXFUDZBAUEZUFZUGZWFXCWRWFWEWBGZXCWFWEWBXDXFUHZBAUIZUJZUGZWGUKULUMUNWSWMSMWSWKPZQDZWMSRZWSNWQHIZXQQWSXQXTWSNCDZXBXCXQXTRYAWSUOUPXKXPNWGUQUFURWSWRXTQDXAWQUSUJUTWSWKCDWKEFXRXSUAWSWGXKXPVAWSWGXKXPVBWKUKULUMUNVCWFWRVDZGZWNWJYCWNWIPZMKZWJYCWMYDMYCWGWFXBYBXJUGZWFXCYBXOUGZWFYBTVEUNYCWICDZYEWJRYCWIVFDZYHYCWHCDYIYCWGYFYGVGWHVHUJWIVIUJWIVJUJVKURVLWFWOWIMVMVNABOVMVNVOZVPUNWFWPWMMWFWPABHIZJKZLKZWMWEWBWPYMRVMVNBAOYJVPVQWFYLWLLWFYKWKJWFWKYKWFXLWKYKRXMBAVRUJURUNUNVKUNVS $.

  gangsym3 $p |- ( ( A e. CC /\ B e. CC /\ C e. CC ) -> ( ( -. A = B /\ -. C = B ) -> ( abs ` ( ( A - B ) ang ( C - B ) ) ) = ( abs ` ( ( C - B ) ang ( A - B ) ) ) ) ) $=
    ( cc wcel w3a wceq wn wa cmin co cang cabs cfv cc0 wne simp1 adantr simp2
    subcld simpl adantl neqned subeq0ad necon3bid mpbird jca simp3 simpr
    gangsym syl ex )
    ADEZBDEZCDEZFZABGZHZCBGZHZIZABJKZCBJKZLKZMNZVCVBLKZMNZGZUPVAIZVBDEZVBOPZIZVCDEZVCOPZIZIVHVIVLVOVIVJVKVIABUPUMVAUMUNUOQZRZUPUNVAUMUNUOSZRZTVIVKABPVIABVAURUPURUTUAUBUCVIVBOABVIABVQVSUDUEUFUGVIVMVNVICBUPUOVAUMUNUOUHZRZVSTVIVNCBPVICBVAUTUPURUTUIUBUCVIVCOCBVICBWAVSUDUEUFUGUGVBVCUJUKUL $.

  gcosabs $p |- ( A e. RR -> ( cos ` ( abs ` A ) ) = ( cos ` A ) ) $=
    ( cr wcel cabs cfv ccos wceq cc0 0re a1i id cle wbr wa absid fveq2d cneg
    absnid cc simpl recnd cosneg syl eqtrd lecasei )
    ABCZADEZFEZAFEZGHAHBCUFIJUFKUFHALMNUGAFAOPUFAHLMZNZUHAQZFEZUIUKUGULFARPUKASCUMUIGUKAUFUJTUAAUBUCUDUE $.

  gangrange $p |- ( ( ( A e. CC /\ A =/= 0 ) /\ ( B e. CC /\ B =/= 0 ) ) -> ( abs ` ( A ang B ) ) e. ( 0 [,] _pi ) ) $=
    ( cc wcel cc0 wne wa cang co cabs cfv cdiv clog cim cpi cicc gangval
    fveq2d cr cle wbr simpr simpld simpl simprd divcl syl3anc jca divne0 syl
    logcld imcld recnd abscl absge0 cneg pire renegcl ax-mp a1i clt logimcl
    syl2anc ltled wb absle mpbir2and w3a 0re elicc2 mpbir3and eqeltrd )
    ACDZAEFZGZBCDZBEFZGZGZABHIZJKBALIZMKZNKZJKZEOPIZVSVTWCJABQRVSWDWEDZWDSDZEWDTUAZWDOTUAZVSWCCDZWGVSWCVSWBVSWAVSVPVMVNWACDZVSVPVQVOVRUBZUCZVSVMVNVOVRUDZUCZVSVMVNWNUEZBAUFZUGZVSVRVOGZWAEFZVSVRVOWLWNUHZBAUIZUJZUKZULZUMZWCUNUJVSWJWHXFWCUOUJVSWIOUPZWCTUAZWCOTUAZVSXGWCXGSDZVSOSDZXJUQOURUSUTXEVSXGWCVAUAZXIVSWKWTXLXIGZWRXCWAVBZVCZUCVDVSXLXIXOUEVSWCSDXKWIXHXIGVEXEXKVSUQUTZWCOVFVCVGVSESDZXKWFWGWHWIVHVEXQVSVIUTXPEOWDVJVCVKVL $.

  gangbnd3 $p |- ( ( A e. CC /\ B e. CC /\ C e. CC ) -> ( ( -. A = B /\ -. C = B ) -> ( ( abs ` ( ( A - B ) ang ( C - B ) ) ) e. RR /\ 0 <_ ( abs ` ( ( A - B ) ang ( C - B ) ) ) ) ) ) $=
    ( cc wcel w3a wceq wn wa cmin co cang cabs cfv cr cc0 cle wbr cpi cicc
    wne simp1 adantr simp2 subcld simpl adantl neqned subeq0ad necon3bid
    mpbird jca simp3 simpr gangrange syl wb 0re a1i pire elicc2 syl2anc mpbid
    simp1d simp2d ex )
    ADEZBDEZCDEZFZABGZHZCBGZHZIZABJKZCBJKZLKZMNZOEZPVSQRZIVJVOIZVTWAWBVTWAVSSQRZWBVSPSTKZEZVTWAWCFZWBVPDEZVPPUAZIZVQDEZVQPUAZIZIZWEWBWIWLWBWGWHWBABVJVGVOVGVHVIUBZUCZVJVHVOVGVHVIUDZUCZUEZWBWHABUAZWBABVOVLVJVLVNUFZUGZUHZWBVPPABWBABWOWQUIZUJZUKZULZWBWJWKWBCBVJVIVOVGVHVIUMZUCZWQUEZWBWKCBUAZWBCBVOVNVJVLVNUNZUGZUHZWBVQPCBWBCBXHWQUIZUJZUKZULZULZVPVQUOZUPZWBPOEZSOEZWEWFUQZYAWBURUSZYBWBUTUSZPSVSVAZVBZVCZVDWBVTWAWCYHVEULVF $.

  glawcos $p |- ( ( ( A e. CC /\ B e. CC /\ C e. CC ) /\ ( -. A = B /\ -. C = B ) ) -> ( ( abs ` ( C - A ) ) ^ 2 ) = ( ( ( ( abs ` ( A - B ) ) ^ 2 ) + ( ( abs ` ( B - C ) ) ^ 2 ) ) - ( 2 x. ( ( ( abs ` ( A - B ) ) x. ( abs ` ( B - C ) ) ) x. ( cos ` ( abs ` ( ( A - B ) ang ( C - B ) ) ) ) ) ) ) ) $=
    ( cc wcel w3a wceq wn wa cmin co cabs cfv c2 cexp caddc cmul cang ccos
    wne simp3 adantr simp1 simp2 3jca simpr adantl neqned simpl jca vx vy
    df-ang eqid lawcos syl2anc abssub oveq1d oveq2d cr cdiv clog cim cc0
    subcld subeq0ad necon3bid mpbird gangval syl divcld divne0d logcld imcld
    eqeltrd gcosabs eqcomd oveq12d eqtrd )
    ADEZBDEZCDEZFZABGZHZCBGZHZIZIZCAJKZLMZNOKZABJKZLMZNOKZCBJKZLMZNOKZPKZNWNWQQKZWMWPRKZSMZQKZQKZJKZWOBCJKZLMZNOKZPKZNWNXGQKZXALMZSMZQKZQKZJKWIWBVTWAFCBTZABTZIWLXEGWIWBVTWAWCWBWHVTWAWBUAZUBZWCVTWHVTWAWBUCZUBZWCWAWHVTWAWBUDZUBZUEWIXOXPWICBWHWGWCWEWGUFZUGZUHZWIABWHWEWCWEWGUIZUGZUHZUJUKULCABRXAWNWQWKUKULUMWNUNWQUNWKUNXAUNUOUPWIWSXIXDXNJWIWRXHWOPWIWQXGNOWIWBWAWQXGGZXRYBCBUQZUPZURUSWIXCXMNQWIWTXJXBXLQWIWQXGWNQYKUSWIXLXBWIXAUTEXLXBGWIXAWPWMVAKZVBMZVCMZUTWIWMDEZWMVDTZIZWPDEZWPVDTZIZIXAYNGWIYQYTWIYOYPWIABXTYBVEZWIYPXPYHWIWMVDABWIABXTYBVFZVGZVHZUJWIYRYSWICBXRYBVEZWIYSXOYEWIWPVDCBWICBXRYBVFZVGZVHZUJUJWMWPVIVJWIYMWIYLWIWPWMUUEUUAUUDVKWIWPWMUUEUUAUUHUUDVLVMVNVOXAVPVJVQVRUSVRVS $.

  gcoscan $p |- ( ( ( X e. CC /\ Y e. CC /\ Z e. CC ) /\ ( K e. CC /\ K =/= 0 ) ) -> ( ( Z - ( 2 x. ( K x. X ) ) ) = ( Z - ( 2 x. ( K x. Y ) ) ) -> X = Y ) ) $=
    ( cc wcel w3a cc0 wne wa c2 cmul co cmin wceq wb simpl simp3 syl 2cn a1i
    simpr simpld simp1 mulcld simp2 subcan syl3anc biimpd 2ne0 jca mulcan
    sylibd )
    BEFZCEFZDEFZGZAEFZAHIZJZJZDKABLMZLMZNMZDKACLMZLMZNMZOZVBVEOZBCOZVAVHVCVFOZVIVAVHVKVAUPVCEFVFEFVHVKPVAUQUPUQUTQZUNUOUPRSVAKVBKEFZVATUAZVAABVAURUSUQUTUBZUCZVAUQUNVLUNUOUPUDZSZUEZUEVAKVEVNVAACVPVAUQUOVLUNUOUPUFZSZUEZUEDVCVFUGUHUIVAVBEFVEEFVMKHIZJVKVIPVSWBVAVMWCVNWCVAUJUAUKVBVEKULUHUMVAUNUOUTVIVJPVRWAVOBCAULUHUM $.

  gangeq $p |- ( ( ( ( A e. CC /\ A =/= 0 ) /\ ( B e. CC /\ B =/= 0 ) ) /\ ( ( C e. CC /\ C =/= 0 ) /\ ( D e. CC /\ D =/= 0 ) ) ) -> ( ( cos ` ( abs ` ( A ang B ) ) ) = ( cos ` ( abs ` ( C ang D ) ) ) -> ( abs ` ( A ang B ) ) = ( abs ` ( C ang D ) ) ) ) $=
    ( cc wcel cc0 wne wa cang co cabs cfv wceq ccos cpi cicc wb simpl
    gangrange syl simpr cos11 syl2anc biimprd )
    AEFZAGHZIZBEFZBGHZIZIZCEFZCGHZIZDEFZDGHZIZIZIZABJKZLMZCDJKZLMZNZVBOMZVDOMZNZUTVBGPQKZFZVDVIFZVEVHRUTULVJULUSSABTUAUTUSVKULUSUBCDTUAVBVDUCUDUE $.

  gsas $p |- ( ( ( P e. CC /\ Q e. CC /\ R e. CC ) /\ ( S e. CC /\ T e. CC /\ U e. CC ) ) -> ( ( ( ( -. P = Q /\ -. Q = R ) /\ -. P = R ) /\ -. ( ( R - P ) / ( Q - P ) ) e. RR ) -> ( ( ( ( -. S = T /\ -. T = U ) /\ -. S = U ) /\ -. ( ( U - S ) / ( T - S ) ) e. RR ) -> ( ( abs ` ( P - Q ) ) = ( abs ` ( S - T ) ) -> ( ( abs ` ( ( P - Q ) ang ( R - Q ) ) ) = ( abs ` ( ( S - T ) ang ( U - T ) ) ) -> ( ( abs ` ( Q - R ) ) = ( abs ` ( T - U ) ) -> ( ( ( ( ( ( abs ` ( P - Q ) ) = ( abs ` ( S - T ) ) /\ ( abs ` ( Q - R ) ) = ( abs ` ( T - U ) ) ) /\ ( abs ` ( R - P ) ) = ( abs ` ( U - S ) ) ) /\ ( abs ` ( ( P - Q ) ang ( R - Q ) ) ) = ( abs ` ( ( S - T ) ang ( U - T ) ) ) ) /\ ( abs ` ( ( Q - R ) ang ( P - R ) ) ) = ( abs ` ( ( T - U ) ang ( S - U ) ) ) ) /\ ( abs ` ( ( R - P ) ang ( Q - P ) ) ) = ( abs ` ( ( U - S ) ang ( T - S ) ) ) ) ) ) ) ) ) ) $=
    ( cc wcel w3a wa wceq wn cmin co cdiv cr cabs cfv cang wi simpr adantr c2
    cexp caddc cmul ccos oveq1d oveq12d fveq2d oveq2d simpl simp1 syl simp2
    simp3 3jca simpld simprd neqned necomd neneqd jca glawcos 3eqtr4d cc0 cle
    wbr wb subcld abscld absge0d sq11 syl2anc mpbid jca31 3eqtr3d eqcomd eqid
    a1i eqtrd wne cpi cicc subeq0ad necon3bid mpbird gangrange 0re pire
    elicc2 simp1d recnd coscl sqcld addcld mulcld absne0d mulne0 gcoscan mpd
    gangeq ex )
    AGHZBGHZCGHZIZDGHZEGHZFGHZIZJZABKZLZBCKZLZJZACKZLZJZCAMNZBAMNZONZPHZLZJZDEKZLZEFKZLZJZDFKZLZJZFDMNZEDMNZONZPHZLZJZABMNZQRZDEMNZQRZKZUUACBMNZSNZQRZUUCFEMNZSNZQRZKZBCMNZQRZEFMNZQRZKZUUEUUQJZYAQRZYOQRZKZJZUULJZUUMACMNZSNZQRZUUODFMNZSNZQRZKZJZYAYBSNZQRZYOYPSNZQRZKZJZTZTZTZTXLYFJZYTUVTUWAYTJZUUEUVSUWBUUEJZUULUVRUWCUULJZUUQUVQUWDUUQJZUVKUVPUWEUVCUVJUWEUVBUULUWEUUEUUQUVAUWDUUEUUQUWCUUEUULUWBUUEUAZUBZUBZUWDUUQUAZUWEUUSUCUDNZUUTUCUDNZKZUVAUWEUUBUCUDNZUUNUCUDNZUENZUCUUBUUNUFNZUUHUGRZUFNZUFNZMNZUUDUCUDNZUUPUCUDNZUENZUCUUDUUPUFNZUUKUGRZUFNZUFNZMNZUWJUWKUWEUWOUXCUWSUXGMUWEUWMUXAUWNUXBUEUWEUUBUUDUCUDUWHUHZUWEUUNUUPUCUDUWIUHZUIZUWEUWRUXFUCUFUWEUWPUXDUWQUXEUFUWEUUBUUDUUNUUPUFUWHUWIUIZUWEUUHUUKUGUWDUULUUQUWCUULUAZUBZUJZUIZUKZUIZUWEXGXNCBKZLZJZJZUWJUWTKZUWEXGUYAUWEXDXEXFUWDXDUUQUWCXDUULUWBXDUUEUWAXDYTXLXDYFXLXGXDXGXKULZXDXEXFUMZUNZUBZUBZUBZUBZUBZUWDXEUUQUWCXEUULUWBXEUUEUWAXEYTXLXEYFXLXGXEUYDXDXEXFUOZUNZUBZUBZUBZUBZUBZUWDXFUUQUWCXFUULUWBXFUUEUWAXFYTXLXFYFXLXGXFUYDXDXEXFUPZUNZUBZUBZUBZUBZUBZUQZUWEXNUXTUWEXNXPUWEXQXSUWEXTYEUWDYFUUQUWCYFUULUWBYFUUEUWAYFYTXLYFUAZUBZUBZUBZUBZURZURZURZUWECBUWEBCUWEBCUWEXNXPVUMUSZUTZVAZVBZVCZVCZABCVDZUNZUWEXKYHFEKZLZJZJZUWKUXHKZUWEXKVVEUWEXHXIXJUWDXHUUQUWCXHUULUWBXHUUEUWAXHYTXLXHYFXLXKXHXGXKUAZXHXIXJUMZUNZUBZUBZUBZUBZUBZUWDXIUUQUWCXIUULUWBXIUUEUWAXIYTXLXIYFXLXKXIVVHXHXIXJUOZUNZUBZUBZUBZUBZUBZUWDXJUUQUWCXJUULUWBXJUUEUWAXJYTXLXJYFXLXKXJVVHXHXIXJUPZUNZUBZUBZUBZUBZUBZUQZUWEYHVVDUWEYHYJUWEYKYMUWEYNYSUWDYTUUQUWCYTUULUWBYTUUEUWAYTUAZUBZUBZUBZURZURZURZUWEFEUWEEFUWEEFUWEYHYJVWPUSZUTZVAZVBZVCZVCZDEFVDZUNZVEZUWEUUSPHZVFUUSVGVHZJZUUTPHZVFUUTVGVHZJZUWLUVAVIZUWEVXGVXHUWEYAUWECAVUEUYKVJZVKZUWEYAVXNVLZVCZUWEVXJVXKUWEYOUWEFDVWIVVOVJZVKZUWEYOVXRVLZVCZUUSUUTVMZVNZVOZVPUXNVCUWEUVFUGRZUVIUGRZKZUVJUWEUWNUWJUENZUCUUNUUSUFNZVYEUFNZUFNZMNZVYHUCVYIVYFUFNZUFNZMNZKZVYGUWEVYLUXBUWKUENZUCUUPUUTUFNZVYFUFNZUFNZMNZVYOUWEUWMUXAVYLWUAUXIUWEXEXFXDIZXPXSJZJUWMVYLKUWEWUBWUCUWEXEXFXDUYRVUEUYKUQUWEXPXSVUOUWEXQXSVULUSZVCVCBCAVDUNUWEXIXJXHIZYJYMJZJUXAWUAKUWEWUEWUFUWEXIXJXHVWBVWIVVOUQUWEYJYMVWRUWEYKYMVWOUSZVCVCEFDVDUNVQUWEVYQVYHVYTVYNMUWEUXBUWNUWKUWJUEUWEUUPUUNUCUDUWEUUNUUPUWIVRZUHUWEUUTUUSUCUDUWEUUSUUTVYDVRZUHZUIUWEVYSVYMUCUFUWEVYRVYIVYFVYFUFUWEUUPUUNUUTUUSUFWUHWUIUIVYFVYFKUWEVYFVSVTUIUKUIWAUWEVYEGHZVYFGHZVYHGHZIZVYIGHZVYIVFWBZJZJVYPVYGTUWEWUNWUQUWEWUKWULWUMUWEUVFGHWUKUWEUVFUWEUVFPHZVFUVFVGVHZUVFWCVGVHZUWEUVFVFWCWDNZHZWURWUSWUTIZUWEUUMGHZUUMVFWBZJZUVDGHZUVDVFWBZJZJZWVBUWEWVFWVIUWEWVDWVEUWEBCUYRVUEVJZUWEWVEBCWBZVUPUWEUUMVFBCUWEBCUYRVUEWEZWFZWGZVCZUWEWVGWVHUWEACUYKVUEVJZUWEWVHACWBZUWEACWUDUTZUWEUVDVFACUWEACUYKVUEWEZWFZWGZVCZVCZUUMUVDWHUNUWEVFPHZWCPHZWVBWVCVIWWEUWEWIVTZWWFUWEWJVTZVFWCUVFWKVNVOWLWMUVFWNUNUWEUVIGHWULUWEUVIUWEUVIPHZVFUVIVGVHZUVIWCVGVHZUWEUVIWVAHZWWIWWJWWKIZUWEUUOGHZUUOVFWBZJZUVGGHZUVGVFWBZJZJZWWLUWEWWPWWSUWEWWNWWOUWEEFVWBVWIVJZUWEWWOEFWBZVWSUWEUUOVFEFUWEEFVWBVWIWEZWFZWGZVCZUWEWWQWWRUWEDFVVOVWIVJZUWEWWRDFWBZUWEDFWUGUTZUWEUVGVFDFUWEDFVVOVWIWEZWFZWGZVCZVCZUUOUVGWHUNUWEWWEWWFWWLWWMVIWWGWWHVFWCUVIWKVNVOWLWMUVIWNUNUWEUWNUWJUWEUUNUWEUUNUWEUUMWVKVKZWMZWOUWEUUSUWEUUSVXOWMZWOZWPUQUWEWUOWUPUWEUUNUUSWXPWXQWQUWEUUNGHZUUNVFWBZJZUUSGHZUUSVFWBZJZJWUPUWEWYAWYDUWEWXSWXTWXPUWEUUMWVKWVOWRVCUWEWYBWYCWXQUWEYAVXNUWEYAVFWBZCAWBZUWECAUWECAUWEACWVSVAZVBZUTZUWEYAVFCAUWECAVUEUYKWEZWFZWGZWRZVCZVCUUNUUSWSUNVCVCVYIVYEVYFVYHWTUNXAUWEWVJWWTJVYGUVJTUWEWVJWWTWWDWXNVCUUMUVDUUOUVGXBUNXAVCUWEUVMUGRZUVOUGRZKZUVPUWEUWJUWMUENZUCUUSUUBUFNZWYOUFNZUFNZMNZWYRUCWYSWYPUFNZUFNZMNZKZWYQUWEXUBUWKUXAUENZUCUUTUUDUFNZWYPUFNZUFNZMNZXUEUWEUWNUXBXUBXUKUXJUWEXFXDXEIZCAKZLZBAKZLZJZJUWNXUBKUWEXULXUQUWEXFXDXEVUEUYKUYRUQUWEXUNXUPWYHUWEBAUWEABUWEABVUNUTZVAZVBZVCVCCABVDUNUWEXJXHXIIZFDKZLZEDKZLZJZJUXBXUKKUWEXVAXVFUWEXJXHXIVWIVVOVWBUQUWEXVCXVEUWEFDUWEDFWXIVAZVBZUWEEDUWEDEUWEDEVWQUTZVAZVBZVCVCFDEVDUNVQUWEXUGWYRXUJXUDMUWEUWKUWJUXAUWMUEWUJUWEUUDUUBUCUDUWEUUBUUDUWHVRZUHUIUWEXUIXUCUCUFUWEXUHWYSWYPWYPUFUWEUUTUUSUUDUUBUFWUIXVLUIWYPWYPKUWEWYPVSVTUIUKUIWAUWEWYOGHZWYPGHZWYRGHZIZWYSGHZWYSVFWBZJZJXUFWYQTUWEXVPXVSUWEXVMXVNXVOUWEUVMGHXVMUWEUVMUWEUVMPHZVFUVMVGVHZUVMWCVGVHZUWEUVMWVAHZXVTXWAXWBIZUWEYAGHZWYEJZYBGHZYBVFWBZJZJZXWCUWEXWFXWIUWEXWEWYEVXNWYLVCZUWEXWGXWHUWEBAUYRUYKVJZUWEXWHBAWBZUWEBAXUTUTZUWEYBVFBAUWEBAUYRUYKWEZWFZWGZVCZVCZYAYBWHUNUWEWWEWWFXWCXWDVIWWGWWHVFWCUVMWKVNVOWLWMUVMWNUNUWEUVOGHXVNUWEUVOUWEUVOPHZVFUVOVGVHZUVOWCVGVHZUWEUVOWVAHZXWTXXAXXBIZUWEYOGHZYOVFWBZJZYPGHZYPVFWBZJZJZXXCUWEXXGXXJUWEXXEXXFVXRUWEXXFFDWBZUWEFDXVHUTZUWEYOVFFDUWEFDVWIVVOWEZWFZWGZVCZUWEXXHXXIUWEEDVWBVVOVJZUWEXXIEDWBZUWEEDXVKUTZUWEYPVFEDUWEEDVWBVVOWEZWFZWGZVCZVCZYOYPWHUNUWEWWEWWFXXCXXDVIWWGWWHVFWCUVOWKVNVOWLWMUVOWNUNUWEUWJUWMWXRUWEUUBUWEUUBUWEUUAUWEABUYKUYRVJZVKZWMZWOWPUQUWEXVQXVRUWEUUSUUBWXQXYHWQUWEWYDUUBGHZUUBVFWBZJZJXVRUWEWYDXYKWYNUWEXYIXYJXYHUWEUUAXYFUWEUUAVFWBABWBXURUWEUUAVFABUWEABUYKUYRWEWFWGWRVCVCUUSUUBWSUNVCVCWYSWYOWYPWYRWTUNXAUWEXWJXXKJWYQUVPTUWEXWJXXKXWSXYEVCYAYBYOYPXBUNXAVCXCXCXCXCXC $.

$}

${
$( Series: the limit of a sequence as the page defines it, and the value
   of a series as the limit of its partial sums. $)
$d j k n $.
$d A j n x $.
$d B j x $.
$d ph j k n x $.

  ${
    climnnre.1 $e |- ( ( ph /\ n e. NN ) -> B e. RR ) $.
    climnnre.2 $e |- ( ph -> A e. RR ) $.
  climnnre $p |- ( ph -> ( ( n e. NN |-> B ) ~~> A <-> A. x e. RR ( 0 < x -> E. j e. NN A. n e. NN ( j <_ n -> ( abs ` ( B - A ) ) < x ) ) ) ) $=
    ( cn cmpt cli wbr cc0 cv clt cle cmin co cabs cfv wi wral cr wrex crp
    crli c1 nnuz cz wcel 1z a1i cc wa recnd eqid fmptd rlimclim ralrimiva wss
    nnssre rlim2 bitr3d ralrp bitrdi cuz wb rexuzre ax-mp uznnssnn ralss syl
    nnz anim12i eluz imbi1d ralbidva bitrd rexbiia bitr3i imbi2i ralbii )
    AFIDJZCKLZMBNZOLZENZFNZPLZDCQRZSTZWEOLZUAZFIUBZEUCUDZUAZBUCUBZWFWNEIUDZUAZBUCUBAWDWOBUEUBZWQAWCCUFLWDWTACWCUGIUHUGUIUJZAUKULAFIDUMWCAWHIUJZUNZDGUOZWCUPUQURABEFIDCADUMUJFIXDUSIUCUTAVAULACHUOVBVCWOBVDVEWPWSBUCWOWRWFWOWLFWGVFTZUBZEIUDZWRXAXGWOVGUKWLEFUGIUHVHVIXFWNEIWGIUJZXFWHXEUJZWLUAZFIUBZWNXHXEIUTXFXKVGWGVJWLFXEIVKVLXHXJWMFIXHXBUNZXIWIWLXLWGUIUJZWHUIUJZUNXIWIVGXHXMXBXNWGVMWHVMVNWGWHVOVLVPVQVRVSVTWAWBVE $.
  $}

  ${
    sersumlim.1 $e |- ( ( ph /\ k e. NN ) -> A e. RR ) $.
    sersumlim.2 $e |- ( ph -> ( n e. NN |-> sum_ k e. ( 1 ... n ) A ) ~~> B ) $.
  sersumlim $p |- ( ph -> sum_ k e. ( ZZ>= ` 1 ) A = B ) $=
    ( c1 cuz cfv csu cn cv cfz co cmpt cli wbr wa wceq vj eqid cz wcel 1z a1i
    cdm climrel releldmi syl cr cc simpl simpr nnuz eleqtrrdi jca recn cvv
    oveq2 sumeq1 sumex fvmptd3 isumclim3 climuni eqcomd )
    ACHIJZBDKZAELHEMZNOZBDKZPZCQRZVLVHQRZSCVHTAVMVNGABUADVLHVGVGUBHUCUDAUEUFAVMVLQUGUDGVLCQUHUIUJADMZVGUDZSZBUKUDZBULUDVQAVOLUDZSVRVQAVSAVPUMVQVOVGLAVPUNUOUPUQFUJBURUJAUAMZVGUDZSZEVTVKHVTNOZBDKZLVLUSVLUBVIVTTVJWCTVKWDTVIVTHNUTVJWCBDVAUJWBVTVGLAWAUNUOUPWDUSUDWBWCBDVBUFVCVDUQCVHVLVEUJVF $.
  $}

$}

