$( abs-bounds, elaborated from proof/triangle-inequality.proof by parley/elaborate.py.
   Everything is built except the statements below, which are
   taken as the readable lines state them: a closure method
   the elaborator does not expand, or a definition the
   database gives no target for. $)

$[ set.mm $]

ine2 $a |- ( A e. RR -> ( ( abs ` A ) e. RR -> A <_ ( abs ` A ) ) ) $.
ine3 $a |- ( A e. RR -> ( ( abs ` A ) e. RR -> -u A <_ ( abs ` A ) ) ) $.

${
  absbound $p |- ( A e. RR -> ( A <_ ( abs ` A ) /\ -u A <_ ( abs ` A ) ) ) $=
    cA cr wcel cc0 cA cle wbr cA cA cabs cfv cle wbr cA cneg cA cabs cfv cle wbr wa cA cc0 clt wbr cA cr wcel cc0 cA cle wbr wa cA cA cabs cfv cle wbr cA cneg cA cabs cfv cle wbr cA cr wcel cc0 cA cle wbr wa cA cabs cfv cr wcel cA cA cabs cfv cle wbr cA cr wcel cc0 cA cle wbr wa cA cc wcel cA cabs cfv cr wcel cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cc wcel cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cr wcel cA cr wcel cc0 cA cle wbr simpl cA cr wcel id syl cA recn syl cA abscl syl cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cabs cfv cr wcel cA cA cabs cfv cle wbr wi cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cr wcel cA cr wcel cc0 cA cle wbr simpl cA cr wcel id syl cA ine2 syl mpd cA cr wcel cc0 cA cle wbr wa cA cabs cfv cr wcel cA cneg cA cabs cfv cle wbr cA cr wcel cc0 cA cle wbr wa cA cc wcel cA cabs cfv cr wcel cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cc wcel cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cr wcel cA cr wcel cc0 cA cle wbr simpl cA cr wcel id syl cA recn syl cA abscl syl cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cabs cfv cr wcel cA cneg cA cabs cfv cle wbr wi cA cr wcel cc0 cA cle wbr wa cA cr wcel cA cr wcel cA cr wcel cc0 cA cle wbr simpl cA cr wcel id syl cA ine3 syl mpd jca cA cr wcel cA cc0 clt wbr wa cA cA cabs cfv cle wbr cA cneg cA cabs cfv cle wbr cA cr wcel cA cc0 clt wbr wa cA cabs cfv cr wcel cA cA cabs cfv cle wbr cA cr wcel cA cc0 clt wbr wa cA cc wcel cA cabs cfv cr wcel cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cc wcel cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cr wcel cA cr wcel cA cc0 clt wbr simpl cA cr wcel id syl cA recn syl cA abscl syl cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cabs cfv cr wcel cA cA cabs cfv cle wbr wi cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cr wcel cA cr wcel cA cc0 clt wbr simpl cA cr wcel id syl cA ine2 syl mpd cA cr wcel cA cc0 clt wbr wa cA cabs cfv cr wcel cA cneg cA cabs cfv cle wbr cA cr wcel cA cc0 clt wbr wa cA cc wcel cA cabs cfv cr wcel cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cc wcel cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cr wcel cA cr wcel cA cc0 clt wbr simpl cA cr wcel id syl cA recn syl cA abscl syl cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cabs cfv cr wcel cA cneg cA cabs cfv cle wbr wi cA cr wcel cA cc0 clt wbr wa cA cr wcel cA cr wcel cA cr wcel cA cc0 clt wbr simpl cA cr wcel id syl cA ine3 syl mpd jca cA cr wcel cc0 cr wcel cA cr wcel wa cc0 cA cle wbr cA cc0 clt wbr wo cA cr wcel cc0 cr wcel cA cr wcel cc0 cr wcel cA cr wcel 0re a1i cA cr wcel id jca cc0 cA lelttric syl mpjaodan $.
$}
