$( even-square, elaborated from proof/sqrt2-irrational.proof by tools/elaborate.py.
   Nothing here is assumed. $)

$[ odd-square.mm $]

${
  evensqua $p |- ( ( A e. ZZ /\ 2 || ( A ^ 2 ) ) -> 2 || A ) $=
    cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr c2 cA cdvds wbr wn wo c2 cA cdvds wbr c2 cA cdvds wbr c2 cA cdvds wbr wn wo cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr exmid a1i cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn wn c2 cA cdvds wbr c2 cA cdvds wbr wn wo c2 cA cdvds wbr wi cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn c2 cA c2 cexp co cdvds wbr wn cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn c2 cA c2 cexp co cdvds wbr wn cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn wa cA cz wcel c2 cA cdvds wbr wn wa c2 cA c2 cexp co cdvds wbr wn cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn wa cA cz wcel c2 cA cdvds wbr wn cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn wa cA cz wcel c2 cA c2 cexp co cdvds wbr wa cA cz wcel cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn simpl cA cz wcel c2 cA c2 cexp co cdvds wbr wa cA cz wcel cA cz wcel cA cz wcel c2 cA c2 cexp co cdvds wbr simpl cA cz wcel id syl syl cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn simpr jca cA oddsquar syl ex cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn c2 cA c2 cexp co cdvds wbr wn wn cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn wa c2 cA c2 cexp co cdvds wbr c2 cA c2 cexp co cdvds wbr wn wn cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn wa cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA c2 cexp co cdvds wbr cA cz wcel c2 cA c2 cexp co cdvds wbr wa c2 cA cdvds wbr wn simpl cA cz wcel c2 cA c2 cexp co cdvds wbr simpr syl c2 cA c2 cexp co cdvds wbr notnot syl ex pm2.65d c2 cA cdvds wbr wn c2 cA cdvds wbr orel2 syl mpd $.
$}
