$( cantor, elaborated from proof/cantor.proof by parley/elaborate.py.
   Nothing here is assumed.
   Checked against a set.mm of 51,256 assertions, sha256
   0d7fb3e59afff60f4cec2287cbb616bf651bbfbf2356a611a43a5c98b5e0462d. $)

$[ definitions.mm $]

${
  $d j m x $.
  $d A j m x $.
  $d B j m x $.
  cantor $p |- ( ( A e. _V /\ B : A --> ~P A ) -> E. j e. ~P A A. x e. A -. ( B ` x ) = j ) $=
    ( cvv wcel cpw wf wa vm cv cfv wn crab wceq wral wrex wss ssrab2 a1i wb simpl id syl rabexg elpwg mpbird simpr fveq2d eleq12d notbid elrab mpbid notnotr eleq2d jca eqcomd wo exmid mpjaodan pm2.21dd ex pm2.18d ralrimiva eqeq2d ralbidv rspcev ) BEFZBBGZCHZIZJKZVLCLZFZMZJBNZVIFZAKZCLZVPOZMZABPZIVSDKZOZMZABPZDVIQVKVQWBVKVQVPBRZWGVKVOJBSTVKVPEFZVQWGUAVKVHWHVKVHVHVHVJUBVHUCUDVOJBEUEUDVPBEUFUDUGVKWAABVKVRBFZIZWAWJWAMZWAWJWKIZVRVPFZWAWLWMWMMZIZWMWLWMWOWNWLWMIZWMWNWLWMUHZWPVRVSFZMZWNWPWIWSIZWSWPWMWTWQWMWTUAZWPVOWSJVRBVLVROZVNWRXBVLVRVMVSXBUCZXBVLVRCXCUIZUJZUKZULZTZUMZWIWSUHZUDZWPWRWMWPVSVPVRWPWLVTWLWMUBZWLWKVTWJWKUHZVTUNZUDZUDZUOZUKZUMZUPZWLWNIZWMWNYAWMWTYAWIWSYAWLWIWLWNUBZWLWJWIWJWKUBZVKWIUHZUDZUDZYAWNWSWLWNUHZYAWMWRYAVPVSVRYAVSVPYAWLVTYBXOUDZUQZUOZUKZUMZUPZXAYAXGTZUGZYGUPZWMWNURZWLWMUSZTZUTZWMWNUBUDWLWOWNYTWMWNUHUDVAVBVCVDUPWFWBDVPVIWCVPOZWEWAABUUAWDVTUUAWCVPVSUUAUCVEUKVFVGUD $.
$}
