$( isosceles, elaborated from proof/isosceles.proof by parley/elaborate.py.
   Nothing here is assumed.
   Checked against a set.mm of 51,256 assertions, sha256
   0d7fb3e59afff60f4cec2287cbb616bf651bbfbf2356a611a43a5c98b5e0462d. $)

$[ geometry.mm $]

${
  isoscele $p |- ( ( ( ( ( A e. CC /\ B e. CC ) /\ C e. CC ) /\ ( ( ( -. A = B /\ -. B = C ) /\ -. A = C ) /\ -. ( ( C - A ) / ( B - A ) ) e. RR ) ) /\ ( abs ` ( C - A ) ) = ( abs ` ( C - B ) ) ) -> ( abs ` ( ( C - A ) ang ( B - A ) ) ) = ( abs ` ( ( C - B ) ang ( A - B ) ) ) ) $=
    ( cc wcel wa wceq wn cmin co cdiv cr cabs cfv cang simpl simpr syl w3a wi id 3jca gtrirotate mpd jca gangsym3 eqcomd abssub eqtrd gtriswap gsas ) ADEZBDEZFZCDEZFZABGZHZBCGZHZFZACGZHZFZCAIJZBAIJZKJZLEZHZFZFZVEMNZCBIJZMNZGZFZVEVFOJZMNZABIJZVMOJZMNZVMVSOJZMNZVPVRVFVEOJZMNZWAVPCAGZHZBAGZHZFZVRWEGZVPWGWIVPUTWGFZWGVPWLWIFZWLVPWMVSVMKJZLEZHZFZWMVPVJWQVPVKVJVKVOPZUPVJQZRZVPULUMUOSZVJWQTZVPULUMUOVPVKULWRVKUPULUPVJPZUPUNULUNUOPZUNULULULUMPZULUAZRZRZRZRZVPVKUMWRVKUPUMXCUPUNUMXDULUMQZRZRZRZVPVKUOWRVKUPUOXCUNUOQZRZRZUBZABCUCZRZUDZWMWPPZRZWLWIPRUTWGQRVPWMWIYCWLWIQRUEVPUOULUMSWJWKTVPUOULUMXQXJXNUBCABUFRUDVPACIJZMNZBCIJZMNZGZVNVLGZFZVFMNZVSMNZGZFZYDYFOJZMNZYFYDOJZMNZGZFZWCVRGZFZWEWAGZFZUUCVPYIUUDVPVLVNVKVOQZUGVPYSYIUUDTZVPVCUTFZYSVPVCUTVPVDVCVPVJVDWTVDVIPZRZVAVCQRVPVAUTVPVDVAUUIVAVCPZRZURUTQRUEVPULUOUMSZUUGYSTVPULUOUMXJXQXNUBZACBUFRUDVPYHYSUUFTZVPYEVNYGVPYEVLVNVPULUOFYEVLGVPULUOXJXQUEACUHRUUEUIVPUOUMFVNYGGVPUOUMXQXNUECBUHRUIVPWQYHUUNTZYAVPVCCBGZHZFZURFZVFVEKJZLEZHZFZWQUUOTZVPVJUVCWTVPXAVJUVCTZXRABCUJZRZUDZVPUULUMUOULSZFUVCUVDTVPUULUVIUUMVPUMUOULXNXQXJUBUEACBBCAUKRUDUDUDUDUDUUBUUCQRUIVPURUUQFZWAWCGZVPURUUQVPVAURUUKURUTPRVPUURUUQVPUUSUURVPUVCUUSUVHUUSUVBPRUURURPRVCUUQQRUEVPXAUVJUVKTXRABCUFRUDUI $.
$}
