$( proof/cantor/cantor, elaborated from proof/cantor.proof by parley/elaborate.py.
   Nothing here is assumed.
   Checked against a set.mm of 51,256 assertions, sha256
   0d7fb3e59afff60f4cec2287cbb616bf651bbfbf2356a611a43a5c98b5e0462d. $)

$[ stdlib/definitions.mm $]

${
  $d i j m x $.
  $d A i j m x $.
  $d B i j m x $.
  cantor $p |- ( ( A e. _V /\ B : A --> ~P A ) -> E. m e. ~P A A. x e. A -. ( B ` x ) = m ) $=
    ( cvv wcel cpw wf wa vi cv vj cfv wn crab wceq wex wral wrex simpl id syl rabexg elisset wss ssrab2 a1i simpr eqcomd sseq1d mpbid wb elpwg mpbird eleq1d eleq2d fveq2d eleq12d notbid elrab notnotr jca wo exmid mpjaodan pm2.21dd ex pm2.18d ralrimiva eqeq2d ralbidv rspcev exlimdv mpd ) BEFZBBGZCHZIZJKZLKZVTCMZFZNZLBOZPZJQZAKZCMZDKZPZNZABRZDVPSZVRWDEFZWFVRVOWNVRVOVOVOVQTZVOUAZUBZWCLBEUCZUBJWDEUDUBVRWEWMJVRWEWMVRWEIZVSVPFZWHVSPZNZABRZIWMWSWTXCWSWDVPFZWTWSXDWDBUEZWSVSBUEZXEWSXEXFXEWSWCLBUFUGWSWDVSBWSVSWDVRWEUHZUIZUJUKWSVSWDBXGUJUKWSWNXDXEULWSVOWNWSVRVOVRWETWQUBWRUBWDBEUMUBUNWSWDVSVPXHUOUKWSXBABWSWGBFZIZXBXJXBNZXBXJXKIZWGVSFZXBXLXMXMNZIZXMXLXMXOXNXLXMIZXMXNXLXMUHZXPWGWHFZNZXNXPXIXSIZXSXPWGWDFZXTXPXMYAXQXPVSWDWGXPXLWEXLXMTZXLXJWEXJXKTZXJWSWEWSXITZXGUBZUBZUBZUPZUKZYAXTULZXPWCXSLWGBVTWGPZWBXRYKVTWGWAWHYKUAZYKVTWGCYLUQZURZUSZUTZUGZUKZXIXSUHZUBZXPXRXMXPWHVSWGXPXLXAYBXLXKXAXJXKUHZXAVAZUBZUBZUPZUSZUKZVBZXLXNIZXMXNUUIYAXMUUIYAXTUUIXIXSUUIXLXIXLXNTZXLXJXIYCWSXIUHZUBZUBZUUIXNXSXLXNUHZUUIXMXRUUIVSWHWGUUIWHVSUUIXLXAUUJUUCUBZUIZUPZUSZUKZVBZYJUUIYPUGZUNZUUIWDVSWGUUIVSWDUUIXLWEUUJYFUBZUIZUPZUKZUUNVBZXMXNVCZXLXMVDZUGZVEZXMXNTUBXLXOXNUVKXMXNUHUBVFVGVHVIVBWLXCDVSVPWIVSPZWKXBABUVLWJXAUVLWIVSWHUVLUAVJUSVKVLUBVGVMVN $.
$}
